Description:
    Adding Subnets to VPC + IGW

Parameters:
    EnvironmentName:
        Description : VPC with Subnets
        Type: String
    VpcCIDR:
        Description : CIDR block for VPC
        Type: String
        Default: "10.0.0.0/16"
    PublicSubnet1CIDR:
        Type: String
        Default: "10.0.1.0/24"
    PublicSubnet2CIDR:
        Type: String
        Default: "10.0.2.0/24"
    PrivateSubnet1CIDR:
        Type: String
        Default: "10.0.3.0/24"
    PrivateSubnet2CIDR:
        Type: String
        Default: "10.0.4.0/24"

Resources:
    myVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock : !Ref VpcCIDR
            EnableDnsHostnames: true
            Tags:
                - Key : Name
                  Value : !Ref EnvironmentName
    myIGW:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key : Name
                  Value : !Ref EnvironmentName
    myIGWattachVPC:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            VpcId: !Ref myVPC
            InternetGatewayId : !Ref myIGW
    myPublicSubnet1:
        Type: AWS::EC2::Subnet 
        Properties:
            VpcId : !Ref myVPC
            AvailabilityZone: !Select [0, !GetAZs '']
            CidrBlock : !Ref PublicSubnet1CIDR
            MapPublicIpOnLaunch : true
            Tags:
                - Key : Name
                  Value : !Sub ${EnvironmentName} Public Subnet (AZ1)
    myPublicSubnet2:
        Type: AWS::EC2::Subnet 
        Properties:
            VpcId : !Ref myVPC
            AvailabilityZone: !Select [1, !GetAZs '']
            CidrBlock : !Ref PublicSubnet2CIDR
            MapPublicIpOnLaunch : true
            Tags:
                - Key : Name
                  Value : !Sub ${EnvironmentName} Public Subnet (AZ2)
    myPrivateSubnet1:
        Type: AWS::EC2::Subnet 
        Properties:
            VpcId : !Ref myVPC
            AvailabilityZone: !Select [0, !GetAZs '']
            CidrBlock : !Ref PrivateSubnet1CIDR
            MapPublicIpOnLaunch : false
            Tags:
                - Key : Name
                  Value : !Sub ${EnvironmentName} Private Subnet (AZ1)
    myPrivateSubnet2:
        Type: AWS::EC2::Subnet 
        Properties:
            VpcId : !Ref myVPC
            AvailabilityZone: !Select [1, !GetAZs '']
            CidrBlock : !Ref PrivateSubnet2CIDR
            MapPublicIpOnLaunch : false
            Tags:
                - Key : Name
                  Value : !Sub ${EnvironmentName} Private Subnet (AZ2)
            
